train:
  seed: 42
  epochs: 100
  log_freq: 1000
  val_freq: 1
  save_freq: 10
  max_grad_norm: 100.
  optimizer:
    type: adam
    lr: 1.e-2
    weight_decay: 5.e-4
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: step
    step_size: 100
    gamma: 1.

datasets:
  type: graph
  root: ./data/discharge/
  threshold: 0.995

model:
  type: gcn
  input_size: 768
  hidden_size: 16
  out_size: 2
  num_layers: 2
  dropout_p: 0.5